#!/bin/bash
gifs=`find . -maxdepth 1 -type f -iname "*.gif"`
if [[ -z $gifs ]]
then
	echo "No gif files present"
	exit 1
fi
bv="980k"
IFS=$'\n'
while :
do
	echo -n "remove .png files after convertion? [y/n] "
	read ans
	ans=${ans^^}
	if [ "$ans" == 'N' ] || [ "$ans" == 'Y' ]
	then
		break
	fi
done
for gif in $gifs
do
	echo "converting file $i"
	f=`echo "$i"|head -c -5`
	ffmpeg -loglevel 16 -y -i "$i" -c:v vp9 -an -b:v "$bv" "$f.webm"
	if [ $? != 0 ]; then
		echo "Something went wrong; exiting" >&2
		unset IFS
		exit 2
	fi
	echo -n "converted file $gif"
	if [ "$ans" == 'Y' ]
	then
		rm -v "$gif"
	fi
done
unset IFS
