#!/bin/bash
gifs = `find . -maxdepth 1 -type f -iname "*.gif"`
if [[ -z $files ]]
then
	echo "No gif files present"
	exit 1
fi
crf="20"
IFS=$'\n'
if [ ! -z ${1+x} ]; then
	crf=$1
fi
for gif in gifs
do
	f=`echo "$i"|head -c -5`
	echo "converting file $gif"
	ffmpeg -loglevel 16 -y -i "$gif" -c:v h264 -an -q:v $crf "$f.mp4"
	if [ $? != 0 ]; then
		echo "Something went wrong; exiting" >&2
		unset IFS
		exit 2
	fi
	echo -n "done; "
	rm -v "$i"
done
unset IFS
