#!/bin/bash
crf="20" # output video quality (lower = better quality)
echo -n "Remove files after converting? "
read ans
if [ -z ${ans+x} ]; then
	ans="y" # assumes yes as default answer
fi
if [ ! -z ${1+x} ]; then
	crf=$1
fi
if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
	for i in *.gif; do
		f=`echo "$i"|head -c -5`
		echo "converting file $i"
		ffmpeg -loglevel 16 -y -i "$i" -c:v h264 -an -q:v $crf "$f.mp4"
		if [ $? != 0 ]; then
			echo "Something went wrong; exiting"
			exit 1
		fi
		echo -n "done; "
		rm -f "$i"
		echo "removed file $i"
	done
else # answered "no" to remove files
	for i in *.gif; do
		f=`echo "$i"|head -c -5`
		echo "converting file $i"
		ffmpeg -loglevel 16 -y -i "$i" -c:v h264 -an -q:v $crf "$f.mp4"
		if [ $? != 0 ]; then
			echo "Something went wrong; exiting"
			exit 1
		fi
	done
fi
