#!/bin/bash
cd "/path/to/folder"
typeset -i num=`ls | cat -n | awk 'END{print $1}'`
echo "Total of $num options"
while :; do
	typeset -i choice=$(( ( RANDOM % $num) + 1 ))
	echo "Chosen one: $choice"
	chosen=`ls | awk "NR==$choice"`
	echo $chosen
	echo -n "One more? [Y/n] "
	read ans
	if [ -z "$ans" ]; then
		ans='y'
	else
		if [ "$ans" != "y" ] && [ "$ans" != "Y" ] ; then
			exit 0
		fi
	fi
	echo
done
exit 2
