#!/bin/bash
echo -n "remove .png files after convertion? [y/n] "
read ans
if [ "$ans" != "y" ] && [ "$ans" != "Y" ] ; then
  for i in *.png; do
    if [ "$i" == "*.png" ] ; then
     echo "No png files present"
     exit 1
    fi
    echo "Converting file $i"
    f=`echo "$i" | head -c -5`
    convert -quality 94 "$i" -background black -alpha remove "$f.jpg"
  done
else
  for i in *.png; do
    if [ "$i" == '*.png' ] ; then
      echo "No png files present"
      exit 1
    fi
    echo "Converting file $i"
    f=`echo "$i" | head -c -5`
    convert -quality 94 "$i" -background black -alpha remove "$f.jpg"
    if (( $? == 0 )); then
			rm "$i"
		else
			exit 2
		fi
    echo "Removed file $i"
  done
fi
