#!/bin/bash
while :
do
	echo -n "remove .png files after convertion? [y/n] "
	read ans
	ans=${ans^^}
	if [ "$ans" == 'N' ] || [ "$ans" == 'Y' ]
	then
		break
	fi
done
if [ "$ans" != "Y" ] ; then
  for i in *.png; do
    if [ "$i" == "*.png" ] ; then
     echo "No png files present"
     exit 1
    fi
    echo "Converting file $i"
    f=`echo "$i" | head -c -4`
    convert -quality 94 "$i" -background black -alpha remove "$f"jpg
  done
else
  for i in *.png; do
    if [ "$i" == '*.png' ] ; then
      echo "No png files present"
      exit 1
    fi
    echo "Converting file $i"
    f=`echo "$i" | head -c -4`
    convert -quality 94 "$i" -background black -alpha remove "$f"jpg
    if (( $? == 0 )); then
      rm -v "$i"
    else
      exit 2
    fi
  done
fi
