#!/bin/bash
files=`find . -maxdepth 1 -type f -iname "*.png"`
if [[ -z $files ]]
then
  echo "No png files present"
  exit 1
fi
IFS=$'\n'
while :
do
	echo -n "remove .png files after convertion? [y/n] "
	read ans
	ans=${ans^^}
	if [ "$ans" == 'N' ] || [ "$ans" == 'Y' ]
	then
		break
	fi
done
for file in $files
do
    echo "Converting file $file"
    f=`echo "$file" | head -c -4`
    convert -quality 94 "$file" -background black -alpha remove "$f"jpg
    if (( $? == 0 ))
    then
      if [ "$ans" == 'Y' ]
      then
        rm -v "$file"
      fi
    else
      unset IFS
      exit 2
    fi
done
unset IFS
