#!/bin/bash
if [ -n "$1" ] && [ -n "$2" ] ; then
	name="$1"
	typeset -i num="$2"
	for i in mpv*.jpg; do
		if (( $num < 10 )); then
			mv $i "$name-0$num.jpg"
			if (( "$?" != 0 )); then
				exit 2
			fi
		else
			mv $i "$name-$num.jpg"
			if (( "$?" != 0 )); then
				exit 2
			fi
		fi
		num=$num+1
	done
	exit 0
else
	echo "Not enough options or more than 2 given."
	exit 1
fi
