#!/bin/bash
if [ -n "$1" ] && [ -n "$2" ] && [ -n "$3" ] ; then
	oldName="$1"
	name="$2"
	typeset -i num="$3"
else
 	if [ -n "$1" ] && [ -n "$2" ] ; then
		oldName="mpv"
		name="$1"
		typeset -i num="$2"
	else
		echo "Usage for renaming mpv*.jpg files:"
		echo "	rename [newName] [number to start counting]"
		echo "or for renaming oldName*.jpg files:"
		echo "	rename [oldName] [newName] [number]"
		exit 1
	fi
fi
for i in "$oldName"*.jpg ; do
	if (( $num < 10 )); then
		mv -i "$i" "$name-0$num.jpg"
		if (( $? != 0 )); then
			exit 2
		fi
	else
		mv -i "$i" "$name-$num.jpg"
		if (( $? != 0 )); then
			exit 2
		fi
	fi
	num=$num+1
done
exit 0

