#!/data/data/com.termux/files/usr/bin/bash

cd /storage/emulated/0/Pictures/Screenshots
for i in *.png
do
	echo "converting file $i"
	f=`echo $i|head -c -5`
	convert -quality 94 "$i" "/storage/sdcard1/Pictures/Screenshots/$f.jpg"
	if (( $? != 0 ))
	then
		echo "Something went wrong"
		exit 1
	fi
	rm $i
	echo "removed file $i"
done
