#!/data/data/com.termux/files/usr/bin/bash
cd /storage/emulated/0/Pictures/Screenshots
files=`find . -maxdepth 1 -type f -iname "*.png"`
IFS=$'\n'
if [[ -z $files ]]
then
	echo "No png files present"
	exit 1
fi
for file in $files
do
	echo "converting file $file"
	f=`echo $file | head -c -4`
	convert -quality 94 "$file" "/storage/emulated/0/Pictures/Screenshots/$fjpg"
	if (( $? != 0 ))
	then
		echo "Something went wrong"
		unset IFS
		exit 2
	fi
	rm -v "$i"
done
unset IFS
